services:
  - docker
addons:
  organization: 'inseefrlab'
script:
  - docker build -t cchemin/shelly .
deploy:
  skip_cleanup: true
  provider: script
  script:
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    && docker push cchemin/shelly
  on:
    branch: ci
